### ISSUE TITLE
Error parsing XML

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#128]
I'm getting this error: `Error Parsing XML` on Project Finish Setup.

![image](https://cloud.githubusercontent.com/assets/434029/25860532/a5d1026a-3503-11e7-9a6b-f4919635e211.png)

But I am unable to find a better explanation from the logs of either running service, or from `docker logs` on any running container.
`

**Comment by danielfdsilva** [comment]
@brunosan the most likely explanation is that there's something going on with the road network. What files are you using?

**Comment by brunosan** [comment]
Indeed. 
I was uploading a `pbf` file (the [country extract](http://download.openstreetmap.fr/extracts/asia/bhutan.osm.pbf)). 

After converting with `osmconvert bhutan.osm.pbf >bhutan.osm`, I could upload the `.osm` file without problems. Thank you.
