### ISSUE TITLE
Docker image not updated

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/Rural-Road-Accessibility#141]
The staging environment is using an old image of `rra-analysis`. We should make sure it always checks for a newer version of the latest dev / stable before running the container. May be enough to run `docker pull wbtransport/rra-analysis:[tag]` before `docker run ...`

Thoughts @danielfdsilva

**Comment by danielfdsilva** [comment]
@olafveerman yes, that's a good idea. We need to be sure the versions match.
