### ISSUE TITLE
Title, Logo

### ISSUE THREAD

**Issue by Holly-Transport** [WorldBank-Transport/Rural-Road-Accessibility#20]
Can we call it: Rural Accessibility Map, as a working title, and throw in the Bank logo (small, anywhere)?  Attached. 

![world_bank_group_logo](https://cloud.githubusercontent.com/assets/4492990/19042522/609134b8-895a-11e6-8419-f646fda943c9.png)

**Comment by cc3065** [comment]
Possible icon making the 2 using WBG guidelines:
![image](https://cloud.githubusercontent.com/assets/8765538/19054791/f727ba94-898e-11e6-9257-87a8700359b7.png)

**Comment by brunosan** [comment]
The looks. 💅 

<img width="1266" alt="screen shot 2016-10-11 at 6 02 49 pm" src="https://cloud.githubusercontent.com/assets/434029/19290278/f71e7c8c-8fdc-11e6-946b-31851f160d5d.png">
