### ISSUE TITLE
Fix "radix" issue in web/src/project.js

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#24]
Missing radix parameter.

https://codeclimate.com/github/WorldBank-Transport/Rural-Road-Accessibility/web/src/project.js#issue_57f44af994b3010001000060

**Comment by brunosan** [comment]
Won't be touching this till we have at least compile tests (#22) on this code.

**Comment by olafveerman** [comment]
Not applicable to new codebase.
