### ISSUE TITLE
Results Page Minor Fixes

### ISSUE THREAD

**Issue by Holly-Transport** [WorldBank-Transport/Rural-Road-Accessibility#33]
(1) Finish work on enabling a file deletion function.
(2) Check bug that prevents correct stats display on comparison table (see screenshot)
(3) Add text / pop-up that explains what the walking-distance function does ;-)

![ss](https://cloud.githubusercontent.com/assets/4492990/20224539/e349b76a-a80c-11e6-936a-1385326ac1d4.png)

**Comment by stvno** [comment]
Bug 2 has been fixed in the last release

**Comment by stvno** [comment]
oh, the results in compare don't get removed with the result, working on it
