### ISSUE TITLE
Don't break when there's only one point

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#37]
the use of `@turf/within` assumes a feature collection. When there's only one point it breaks. This also happens for example when we split the region into squares and there's only one point.

Force input to be a feature collection.

**Comment by brunosan** [comment]
This might still be relevant. Leaving open to investigate.

**Comment by danielfdsilva** [comment]
No longer a problem. POI have to be a `FeatureCollection`
