### ISSUE TITLE
Should we implement this tools a QGIS plugin?

### ISSUE THREAD

**Issue by brunosan** [WorldBank-Transport/Rural-Road-Accessibility#38]
Meaning we finish the minimal requirement here and then we re-implement dropping the website interface.  Instead we make it a plugin you install on QGIS, like all the other thousands

Benefits:
- Doing so forces it to be more modular, which would allow more use cases.
- Minimal coding effort on the interface, we use QGIS.
- Minimal coding effort on the visualizations, we use QGIS.
- Instant applicability to anyone everywhere using QGIS. No install, cloud interface, ...
- No "who hosts this" issues.

Problems:
- We still need to do the `osrm` heavy lifting, possibility on the cloud anyways.
- More coding involved to make it talk to QGIS.

**Comment by GeoWBG** [comment]
Tend to agree, but can see some pitfalls. Who will/can do the heavy lifting?

**Comment by brunosan** [comment]
Same as current approach. Us, with contributions from others. The only difference would be that instead of running a website and doing training on it, we would do training on QGIS and pull it up as a "plugin" from the registry.

**Comment by Holly-Transport** [comment]
Hmmm.

But this goes against a number of our short-term objectives. I know, from a
developer / GIS professional perspective, a QGIS plugin makes sense, but in
our weird international development world, a plugin poses quite a number of
hurdles.  For the sake of transparency, I can prepare an argument here, but
in the interim, for expediency, happy to chat in person. :-)

In short, there are instances when you really do need a web-based
application to mainstream new approaches...

H

**Comment by stvno** [comment]
`osrm` is not really supported for windows: https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation also running `osrm` requires quite some resources, especially memory, which might not be available on (WBG) laptops. 
A hybrid solution might also be an option: put `osrm` in the cloud and use the QGIS plugin to manage data and visualize results. Still requires someone with gis-plugin experience

**Comment by brunosan** [comment]
As decided today in the meeting, for now it's going to be a stand-alone server that can run locally, on a server; and has minimal visualization widgets, so we offload what is not core scope.
