### ISSUE TITLE
calculateETA error

### ISSUE THREAD

**Issue by dalekunce** [WorldBank-Transport/Rural-Road-Accessibility#40]
@emilyeros and I got everything configured and running but caculateETA crashes. Would love some help.

<img width="935" alt="screen shot 2017-01-03 at 5 27 15 pm" src="https://cloud.githubusercontent.com/assets/1913857/21629110/02b62074-d1da-11e6-84f1-b4ad275d1ceb.png">

**Comment by stvno** [comment]
It looks like it cannot find an osrm file to work with
do you have a ./web/data/config.json with the proper path to the *.osrm file in baseline:

```
"baseline":{
  "name":"baseline"
  ,"dir":"./web/data/project_1463767649122/baseline",
  "files":{
    "osm":"baseline.osm",
    "profile":"profile.lua",
    "osrm":"baseline.osrm"
   }
```

**Comment by stvno** [comment]
It might be the same as #41 did you run osrm-contract on the .osrm file?

**Comment by brunosan** [comment]
Closing here, as this seem to come from current `master`, `v0.2.0` branch has many changes.
