### ISSUE TITLE
Problems encountered when running the app

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/Rural-Road-Accessibility#41]
Installing and getting the app up was pretty simple and straightforward.
The problems started when trying to feed it data.

I cloned the app repo and checked out the `Jamaica` branch and copied the data fixtures used for testing. `test/fixtures/data` to `web/`

Since I noticed that there wasn't any `.osm` or `.osrm` file I checked the `master` branch. There wasn't any `.osm` file there as well but I found [JM.pbg](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/blob/master/test/fixtures/data/JM.pbf) which I converted to `.osm` using [this script](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/blob/master/test/prepare-test.sh).

I then followed the instruction on the [OSRM import README](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/tree/Jamaica/scripts/OSRM%20import).

Running the command `./osrm-extract map.osm` gives this error:
```
[error] Profile profiles/car.lua not found!
```

so I tried `./osrm-extract -p profile.lua map.osm` but I get:
```
[info] Using script profile.lua
[info] Input file: map.osm
[info] Profile: profile.lua
[info] Threads: 8
[info] Parsing in progress..
[STXXL-MSG] STXXL v1.4.1 (prerelease/Debug)
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 2500 MiB, I/O implementation: memory queue=0 devid=0
[info] input file generated by Osmosis 0.45
[info] timestamp: n/a
[info] Found no turn restriction tags
TBB Warning: Exact exception propagation is requested by application but the linked library is built without support for it
terminate called after throwing an instance of 'tbb::captured_exception'
  what():  lua: error: lua: error: profile.lua:388: sol: attempt to index (set) lua_nil value "is_access_restricted" on userdata (bad (misspelled?) key name or does not exist)
Aborted (core dumped)
```

I tried commenting the lines 381-389 in `profile.lua` and the processing worked. However I don't know the implications of doing this. It may remove important data.

I then tried to run the app with the new generated file, but I'm getting another error when I try to generate the dataset.
```
Location of OSRM:  /srv/rra/./web/data/project_1463767649122/baseline/JM.osrm
/srv/rra/scripts/node/calculateETA.js:26
  var osrm = new OSRM(e.osrm);
             ^

TypeError: Invalid file paths given!
    at TypeError (native)
    at process.<anonymous> (/srv/rra/scripts/node/calculateETA.js:26:13)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/srv/rra/node_modules/signal-exit/index.js:155:32)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
I verified that the file does exist in that path, so I'm not sure why it is failing.

cc @olafveerman

**Comment by stvno** [comment]
Which OSRM version are you using? The profile.lua files and node-osrm are very sensitive to the specific OSRM versions. I generally build a release version of OSRM, use the profile.lua as it is included in the release tar ball and make sure that the node-osrm is using the same version.

Also OSRM can handle .pbf files as well, no need to convert to .osm

**Comment by stvno** [comment]
I'm trying to recreate it and I noticed that if you only do `osrm-extract JM.pbf` and not the next step `osrm-contract JM.osrm` you get the `TypeError: Invalid file paths given!` error.

**Comment by danielfdsilva** [comment]
@stvno 

Ok, I tried to start from scratch. This is what I did this time:
- Latest code from Jamaica branch
- Copy `test/fixtures/data` to `web`
- Get `JM.pbf` from `master`
- Build osrm 5.4.0
- Build failing. Solved with https://github.com/Project-OSRM/osrm-backend/issues/1196#issuecomment-277220177
- Convert `JM.pbf` to `JM.osrm`, following the instructions in `scripts/OSRM import`
- Copy `JM.osrm*` to `web/data/project_1463767649122/baseline`
- Run

It works now. Clicking on a province generates the result csv, but it's empty.
The only output in the console is: `No villages within batch`.
Is the village data for another area?

**Comment by danielfdsilva** [comment]
@stvno figured out what was causing the problem.
- In [calculateETA.js#L189](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/blob/Jamaica/scripts/node/calculateETA.js#L189) villages is already a featureCollection
- In [calculateETA.js#L202](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/blob/Jamaica/scripts/node/calculateETA.js#L202) it is also already a featureCollection

Once you remove those functions it works. Not sure what impact this has but works for the demo data.

**Comment by stvno** [comment]
hm, I know the application assumes and doesn't check if data is already in a featurecollection. But not sure why it failed on the test data. @brunosan any idea why this fails?

**Comment by olafveerman** [comment]
With the new codebase, this is outdated.
