### ISSUE TITLE
Investigate iD backend

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/Rural-Road-Accessibility#43]
The iD editor is able to edit osm data as long as the needed APIs are available. We need to investigate what's the best backend to use to make sure integration is smooth.

cc @kamicut

**Comment by kamicut** [comment]
For the backend, we need an OSM compatible server. Out of the box, we can use https://github.com/developmentseed/macrocosm or https://github.com/digidem/osm-p2p-server

What we will need to implement scenarios:
- Adding scenario tags to all the items edited on the frontend (`scenario=scenarion_1`)
- A custom id (using a [modified OSM service](https://github.com/openstreetmap/iD/blob/master/API.md#customized-deployments)) that hits endpoints at `/:scenario/{everything}`
- A server api prefix route that filters the data according to the prefix

**Comment by danielfdsilva** [comment]
From the meeting with @kamicut and @olafveerman 
Going to implement this using the [osm-p2p-server](https://github.com/digidem/osm-p2p-server).
To simplify data handling we'll have a database for each scenario. This will allow us to minimize the needed changes and when adding a new scenario we can just clone the database.

iD will have to be modified (or use the new iD's plugin system) to include information about what database the server needs to connect to (most likely to be done through a path prefix that will include the project and scenario's ids).

Importing data from the `.osm` file the user uploads will most likely be done with the changeset api. @olafveerman to provide instructions on how to convert the file to a changeset.

To export the data back to `.osm` format (to be consumed by OSRM), we'll see if it is feasible to use the `/api/0.6/map` endpoint with a worldwide bbox. If this proves impossible, we'll implement an export function that taps directly into the database.

**Comment by danielfdsilva** [comment]
Related to #59 
I've been trying out the [osm-p2p-server](https://github.com/digidem/osm-p2p-server). This is a log of what I did so far and the problems I found.

### Integration with Hapi
osm-p2p-server is made to work directly with node's http server, which means tapping directly into the raw http request. On Hapi this is found in `request.raw`. Another issue here is that the osm-p2p-server router expects the data to be a stream. This can be configured in Hapi through a rather obscure property. For posterity here's the route code.

```
{
  path: '/api/0.6/{path*}',
  method: '*',
  config: {
    // Ensure that the payload is still a stream so the osm-p2p-server
    // can handle.
    payload: {
      output: 'stream'
    }
  },
  handler: (request, reply) => {
    let req = request.raw.req;
    let res = request.raw.res;

    if (!router.handle(req, res)) {
      return reply('Not Found');
    }
  }
}
```

### Multiple dbs
The database has to be selected for each request, based on the project and scenario ids.
This is done easily by initializing the osm-p2p-server router on the route handler rather then outside. Something to keep in mind though is that the db connection stays open and a new connection on the same db can't be established. This is easily solved by keeping and index of db connections.

### Data upload
Data can be uploaded to the database using the changeset endpoint: `POST /api/0.6/changeset/:id/upload`.
The data has to be a proper osm changeset and each node/way has to have the changeset id.
Example:
```
<?xml version="1.0"?>
<osmChange version="0.3" generator="uvmogr2osm">
<create>

  <node id="-2" changeset='1' lat="-11.6572028" lon="27.4691154" visible="true"/>
  <node id="-3" changeset='1' lat="-11.6570032" lon="27.4688649" visible="true"/>
  <node id="-4" changeset='1' lat="-11.6567879" lon="27.4684879" visible="true"/>
  <node id="-5" changeset='1' lat="-11.6557674" lon="27.4664466" visible="true"/>
  <node id="-6" changeset='1' lat="-11.655604" lon="27.4659408" visible="true"/>

  <way id="-1" changeset='1' visible="true">
    <nd ref="-2"/>
    <nd ref="-3"/>
    <nd ref="-4"/>
    <nd ref="-5"/>
    <nd ref="-6"/>
    <tag k="z_order" v="6"/>
    <tag k="osm_id" v="4709653"/>
    <tag k="highway" v="secondary"/>
    <tag k="name" v="Boulevard Kamanyola"/>
  </way>

</create>
<modify/>
<delete if-unused="true"/>
</osmChange>
```

### Problems
Uploading data has proven to be a very slow process.
I ran a test with a ~ 9MB file and the upload took a staggering 77 seconds.
This is a processing speed of roughly 120KB/s.

I looked into the osm-p2p-server's files and timed some of the functions, the results follow:

file: https://github.com/digidem/osm-p2p-server/blob/master/routes/changeset_upload.js
```
osm2Obj: 2341.864ms // Converting from osm to js object

api.putChanges: 76289.831ms // Expanded below
```

The internals of the function `api.putChanges` are in https://github.com/digidem/osm-p2p-server/blob/master/api/put_changes.js

```
// Validations are pretty fast
validateChangeset: 2.653ms
validateChangesetIds: 5.851ms
filterSafeDeletes: 111.431ms

replacePlaceholderIds: 2563.292ms // Replacing ids with generated ones

osm.batch: 73314.608ms // Core function to add data to the db
```

The `osm.batch` function is from the `osm-p2p-db` defined in https://github.com/digidem/osm-p2p-db/blob/master/index.js#L205. After some more data processing this function calls `self.kv.batch` which is part [hyperkv's api](https://github.com/substack/hyperkv#kvbatchrows-opts-cb).
Leveldb (used as data storage) should be pretty fast, my guess is that maybe hyperkv is the bottleneck.

---

Just for the sake of it I also ran a test with a ~720MB file which, had it worked, it would have taken something short of 1:45 hours (Assuming a linear time complexity).
This import failed after some time because the v8 engine reach the memory limit.

One possible solution would be to split the data into several imports (possibly parallel?). This split would have to be a logical one, keeping the related ways and nodes on the same import.
However even with this approach we're talking about a long processing time since files over or near 1GB are to be expected.

**Comment by danielfdsilva** [comment]
Related to #59 
I've been trying out the [osm-p2p-server](https://github.com/digidem/osm-p2p-server). This is a log of what I did so far and the problems I found.

### Integration with Hapi
osm-p2p-server is made to work directly with node's http server, which means tapping directly into the raw http request. On Hapi this is found in `request.raw`. Another issue here is that the osm-p2p-server router expects the data to be a stream. This can be configured in Hapi through a rather obscure property. For posterity here's the route code.

```
{
  path: '/api/0.6/{path*}',
  method: '*',
  config: {
    // Ensure that the payload is still a stream so the osm-p2p-server
    // can handle.
    payload: {
      output: 'stream'
    }
  },
  handler: (request, reply) => {
    let req = request.raw.req;
    let res = request.raw.res;

    if (!router.handle(req, res)) {
      return reply('Not Found');
    }
  }
}
```

### Multiple dbs
The database has to be selected for each request, based on the project and scenario ids.
This is done easily by initializing the osm-p2p-server router on the route handler rather then outside. Something to keep in mind though is that the db connection stays open and a new connection on the same db can't be established. This is easily solved by keeping and index of db connections.

### Data upload
Data can be uploaded to the database using the changeset endpoint: `POST /api/0.6/changeset/:id/upload`.
The data has to be a proper osm changeset and each node/way has to have the changeset id.
Example:
```
<?xml version="1.0"?>
<osmChange version="0.3" generator="uvmogr2osm">
<create>

  <node id="-2" changeset='1' lat="-11.6572028" lon="27.4691154" visible="true"/>
  <node id="-3" changeset='1' lat="-11.6570032" lon="27.4688649" visible="true"/>
  <node id="-4" changeset='1' lat="-11.6567879" lon="27.4684879" visible="true"/>
  <node id="-5" changeset='1' lat="-11.6557674" lon="27.4664466" visible="true"/>
  <node id="-6" changeset='1' lat="-11.655604" lon="27.4659408" visible="true"/>

  <way id="-1" changeset='1' visible="true">
    <nd ref="-2"/>
    <nd ref="-3"/>
    <nd ref="-4"/>
    <nd ref="-5"/>
    <nd ref="-6"/>
    <tag k="z_order" v="6"/>
    <tag k="osm_id" v="4709653"/>
    <tag k="highway" v="secondary"/>
    <tag k="name" v="Boulevard Kamanyola"/>
  </way>

</create>
<modify/>
<delete if-unused="true"/>
</osmChange>
```

### Problems
Uploading data has proven to be a very slow process.
I ran a test with a ~ 9MB file and the upload took a staggering 77 seconds.
This is a processing speed of roughly 120KB/s.

I looked into the osm-p2p-server's files and timed some of the functions, the results follow:

file: https://github.com/digidem/osm-p2p-server/blob/master/routes/changeset_upload.js
```
osm2Obj: 2341.864ms // Converting from osm to js object

api.putChanges: 76289.831ms // Expanded below
```

The internals of the function `api.putChanges` are in https://github.com/digidem/osm-p2p-server/blob/master/api/put_changes.js

```
// Validations are pretty fast
validateChangeset: 2.653ms
validateChangesetIds: 5.851ms
filterSafeDeletes: 111.431ms

replacePlaceholderIds: 2563.292ms // Replacing ids with generated ones

osm.batch: 73314.608ms // Core function to add data to the db
```

The `osm.batch` function is from the `osm-p2p-db` defined in https://github.com/digidem/osm-p2p-db/blob/master/index.js#L205. After some more data processing this function calls `self.kv.batch` which is part [hyperkv's api](https://github.com/substack/hyperkv#kvbatchrows-opts-cb).
Leveldb (used as data storage) should be pretty fast, my guess is that maybe hyperkv is the bottleneck.

---

Just for the sake of it I also ran a test with a ~720MB file which, had it worked, it would have taken something short of 1:45 hours (Assuming a linear time complexity).
This import failed after some time because the v8 engine reach the memory limit.

One possible solution would be to split the data into several imports (possibly parallel?). This split would have to be a logical one, keeping the related ways and nodes on the same import.
However even with this approach we're talking about a long processing time since files over or near 1GB are to be expected.

cc @olafveerman @kamicut

**Comment by gmaclennan** [comment]
Thanks for this investigation @danielfdsilva, at a quick glance I suspect that this slowdown is being caused by https://github.com/substack/hyperkv/blob/master/index.js#L286 which _I think_ is trying to check whether this is an update to an existing document, or creation of a new document.

@substack any insight here?

I haven't parsed all the code, but I have a feeling that if you changed https://github.com/digidem/osm-p2p-server/blob/master/api/put_changes.js#L77-L81 to:

```js
  var op = {
    type: change.action === 'delete' ? 'del' : 'put',
    key: change.id,
    value: {},
    links: []
  }
```

it _might_ speed things up because the hyperkv code would not look for links that are not there. The put changes API is designed to be atomic, not sure if this decreases or increases performance?

Would be interested to know if you tried adding `links: []` as I say above if it would (a) break things or (b) make it work faster or (c) do nothing.

**Comment by gmaclennan** [comment]
re. integration with Hapi this is how you might do it with Express https://github.com/digidem/osm-p2p-server#use-as-express-middleware although at a quick glance at Hapi it looks like it really hides the vanilla http methods behind a lot of magic so it may be more tricky. I tried to design the osm-p2p-server api so that was framework agnostic, and the basic router we use is entirely optional. Needs more docs.

**Comment by danielfdsilva** [comment]
@gmaclennan I tried adding `links: []` as you suggested, but no improvement. The result is still the same.
