### ISSUE TITLE
Data examples

### ISSUE THREAD

**Issue by danielfdsilva** [WorldBank-Transport/Rural-Road-Accessibility#60]
Examples for the different file types:
- road network
- profile
- pois
- admin boundaries
- villages

These need to be all part of the same project (it's not useful to have road network of jamaica and villages in china).

Ideally we'd have a couple of small example files, and a bigger one representing a more real use case.

**Comment by olafveerman** [comment]
Sample data for the Western part of Sergipe: [townhalls-sergipe.zip](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/files/859069/townhalls-sergipe.zip)

@danielfdsilva

**Comment by olafveerman** [comment]
Closing this issue. I'm sure we'll need to tweak it, but we can open other issues for that.
