### ISSUE TITLE
iD data export to OSM

### ISSUE THREAD

**Issue by olafveerman** [WorldBank-Transport/Rural-Road-Accessibility#91]

**Comment by olafveerman** [comment]
Using the test data from https://github.com/WorldBank-Transport/Rural-Road-Accessibility/issues/60#issuecomment-288153841, I generated an export from the
[osmp2p db](https://github.com/WorldBank-Transport/Rural-Road-Accessibility/files/861474/osmp2p-map-test.xml.zip). 

Endpoint used `http://localhost:4000/projects/1002/scenarios/1000/osm/map?bbox=-180,-90,180,90`

Next step:

- [ ] 'stress test' with dense extracts (1GB) @olafveerman
- [ ] test exported OSM with OSRM @danielfdsilva

**Comment by danielfdsilva** [comment]
@olafveerman Did a test converting the file to osrm. It is failing saying it can't parse the timestamps.
```
[info] Using script profile.lua
[info] Input file: road-network-exported.xml
[info] Profile: profile.lua
[info] Threads: 8
[info] Parsing in progress..
[STXXL-MSG] STXXL v1.4.1 (prerelease/Release)
[STXXL-MSG] Disk '/var/tmp/stxxl' is allocated, space: 2500 MiB, I/O implementation: memory queue=0 devid=0
[info] input file generated by obj2osm
[info] timestamp: n/a
[info] Found no turn restriction tags
terminate called after throwing an instance of 'std::invalid_argument'
  what():  can not parse timestamp
Aborted (core dumped)
```
